ActionReply: remove operator<< and operator>>
Looks for QMetaTypes in Qt6, if you define an operator<</>> it needs to be
exported and visible to the linker:

in function `QtPrivate::QDataStreamOperatorForType<KAuth::ActionReply, true>::dataStreamOut(QtPrivate::QMetaTypeInterface const*, QDataStream&, void const*)':
/usr/include/qt6/QtCore/qmetatype.h:2229: undefined reference to `KAuth::operator<<(QDataStream&, KAuth::ActionReply const&)'

Instead do what Volker suggested, remove the operators and basically fold
their code into the serialized/deserialized() methods.